# version: '3'
services:
  clash: # Clash 内核
    container_name: clash-meta
    image: metacubex/mihomo:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./clash:/root/.config/mihomo

  metacubexd: # Clash WebUI
    container_name: metacubexd
    image: ghcr.io/metacubex/metacubexd
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: "28002"
      DEFAULT_BACKEND_URL: "http://127.0.0.1:28001"
    volumes:
      - ./caddy:/config/caddy
