# version: '3'
services:
  clash: # Clash 内核
    container_name: clash-meta
    image: metacubex/mihomo:latest
    restart: unless-stopped
    ports:
      - '7890:7890'
      - '28001:28001'
    volumes:
      - ./clash:/root/.config/mihomo

  metacubexd: # Clash WebUI
    container_name: metacubexd
    image: ghcr.io/metacubex/metacubexd
    restart: unless-stopped
    ports:
      - '127.0.0.1:28002:80'
    volumes:
      - ./caddy:/config/caddy