mixed-port: 7890
allow-lan: true
external-controller: 127.0.0.1:28001
secret: 8a09518e-5d92-4a7e-b811-9dfd3b611842

mode: rule
proxies:

proxy-groups:
  - name: "我的跳板"
    type: select
    use:
     - "第三方订阅"
  - name: "第三方订阅"
    type: select
    use:
     - "第三方订阅"

# URL 延迟检测 通用配置
my-url-test: &my-url-test
  # 延迟检测 URL
  health-check:
    enable: true
    url: https://cp.cloudflare.com
    # 节点连通性检测时间，单位为秒
    interval: 300
    # 节点超时延迟，单位为毫秒
    timeout: 1000
    # 节点自动切换差值，单位为毫秒
    tolerance: 100

proxy-providers:
  "第三方订阅":
    type: http
    url: "https://64.186.228.21:54321/api/v1/client/subscribe?token=a42684e9a1a0ec59f6309b501732786d"
    path: /root/.config/mihomo/di3fang.yaml
    # 自动更新订阅时间，单位为秒
    interval: 3600 # 一小时
    # URL 延迟检测逻辑
    <<: *my-url-test

dns:
  enable: true
  ipv6: true
  nameserver:
    - https://[2606:4700:4700::1111]/dns-query
    - 223.5.5.5
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP

rules:
  #- PROCESS-PATH,/usr/bin/xray,DIRECT
  - PROCESS-NAME,ddns-go,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,qbittorrent-nox,DIRECT
  - MATCH,我的跳板

tun:
  enable: false
  stack: system
  auto-route: true
  auto-detect-interface: true
